version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-nizam}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12345}
      POSTGRES_DB: ${DB_NAME:-nizam_main}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db-data-prod:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env.production
    env_file:
      - .env.production
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db-data-prod:
    driver: local
